"""create_all_tables

Revision ID: 3c22fa465150
Revises: 
Create Date: 2026-03-08 15:16:44.717528

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '3c22fa465150'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_extraction',
    sa.Column('extraction_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('entity_type', sa.String(length=32), nullable=False),
    sa.Column('entity_id', sa.BigInteger(), nullable=False),
    sa.Column('extracted_label', sa.String(length=64), nullable=False),
    sa.Column('extracted_value', sa.String(length=128), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('evidence_text', sa.Text(), nullable=True),
    sa.Column('model_version', sa.String(length=64), nullable=True),
    sa.Column('extraction_status', sa.String(length=16), nullable=True),
    sa.Column('reviewed_by', sa.BigInteger(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('extraction_id')
    )
    op.create_table('interaction_event',
    sa.Column('event_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_a_id', sa.BigInteger(), nullable=False),
    sa.Column('user_b_id', sa.BigInteger(), nullable=False),
    sa.Column('event_type', sa.String(length=32), nullable=False),
    sa.Column('event_time', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('outcome_label', sa.String(length=32), nullable=True),
    sa.Column('willingness_a', sa.String(length=32), nullable=True),
    sa.Column('willingness_b', sa.String(length=32), nullable=True),
    sa.Column('issue_tags_json', sa.JSON(), nullable=True),
    sa.Column('memo_ref_id', sa.BigInteger(), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_table('interaction_memo',
    sa.Column('memo_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('related_event_id', sa.BigInteger(), nullable=False),
    sa.Column('author_id', sa.BigInteger(), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('summary_text', sa.String(length=1024), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('memo_id')
    )
    op.create_table('recommendation_snapshot',
    sa.Column('rec_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('requester_user_id', sa.BigInteger(), nullable=False),
    sa.Column('candidate_user_id', sa.BigInteger(), nullable=False),
    sa.Column('safety_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('chat_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('second_date_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('conflict_risk_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('verify_count', sa.Integer(), nullable=True),
    sa.Column('final_rank_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('explanation_json', sa.JSON(), nullable=True),
    sa.Column('snapshot_stage', sa.String(length=16), nullable=True),
    sa.Column('verify_pending_count', sa.Integer(), nullable=True),
    sa.Column('verify_task_ids', sa.JSON(), nullable=True),
    sa.Column('rank_change_reason', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('rec_id')
    )
    op.create_table('user_constraint',
    sa.Column('constraint_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('tag_code', sa.String(length=64), nullable=False),
    sa.Column('tag_type', sa.String(length=16), nullable=False),
    sa.Column('direction', sa.String(length=16), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('source_type', sa.String(length=32), nullable=True),
    sa.Column('source_ref_id', sa.BigInteger(), nullable=True),
    sa.Column('is_human_confirmed', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=True),
    sa.Column('constraint_scope', sa.String(length=32), nullable=True),
    sa.Column('applies_to_field', sa.String(length=64), nullable=True),
    sa.Column('confirm_required', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('constraint_id')
    )
    op.create_table('user_observation_tag',
    sa.Column('tag_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('tag_code', sa.String(length=64), nullable=False),
    sa.Column('tag_value', sa.String(length=64), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('observer_type', sa.String(length=16), nullable=True),
    sa.Column('source_ref_id', sa.BigInteger(), nullable=True),
    sa.Column('valid_from', sa.DateTime(), nullable=True),
    sa.Column('valid_to', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('tag_id')
    )
    op.create_table('user_preference',
    sa.Column('preference_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('dimension', sa.String(length=64), nullable=False),
    sa.Column('operator', sa.String(length=16), nullable=False),
    sa.Column('value_json', sa.JSON(), nullable=True),
    sa.Column('priority_level', sa.String(length=16), nullable=True),
    sa.Column('source_type', sa.String(length=32), nullable=True),
    sa.Column('confirmed_by_matchmaker', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('preference_id')
    )
    op.create_table('user_profile',
    sa.Column('user_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('gender', sa.String(length=16), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('height_cm', sa.Integer(), nullable=True),
    sa.Column('city_code', sa.String(length=32), nullable=True),
    sa.Column('education_level', sa.String(length=32), nullable=True),
    sa.Column('marital_status', sa.String(length=32), nullable=True),
    sa.Column('occupation', sa.String(length=64), nullable=True),
    sa.Column('smoking_status', sa.String(length=32), nullable=True),
    sa.Column('drinking_status', sa.String(length=32), nullable=True),
    sa.Column('pet_status', sa.String(length=32), nullable=True),
    sa.Column('open_to_match', sa.Integer(), nullable=True),
    sa.Column('active_status', sa.String(length=32), nullable=True),
    sa.Column('profile_completeness', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('verification_status', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('verify_task',
    sa.Column('task_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('requester_user_id', sa.BigInteger(), nullable=False),
    sa.Column('candidate_user_id', sa.BigInteger(), nullable=False),
    sa.Column('verify_field', sa.String(length=64), nullable=False),
    sa.Column('trigger_reason', sa.String(length=255), nullable=True),
    sa.Column('rough_rank_score', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('task_status', sa.String(length=32), nullable=True),
    sa.Column('confirmed_value', sa.String(length=128), nullable=True),
    sa.Column('confirmed_by', sa.BigInteger(), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('task_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('verify_task')
    op.drop_table('user_profile')
    op.drop_table('user_preference')
    op.drop_table('user_observation_tag')
    op.drop_table('user_constraint')
    op.drop_table('recommendation_snapshot')
    op.drop_table('interaction_memo')
    op.drop_table('interaction_event')
    op.drop_table('ai_extraction')
    # ### end Alembic commands ###

